# Generated by Django 5.2.11 on 2026-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('LEVEL1', 'Level 1: MCQ Pending'), ('LEVEL2', 'Level 2: Voice Pending'), ('LEVEL3', 'Level 3: HR Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('ats_score', models.IntegerField(default=0)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
