# Generated by Django 5.2.11 on 2026-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_score', models.IntegerField(default=0, help_text='Level 1 Score')),
                ('mcq_passed', models.BooleanField(default=False)),
                ('voice_audio', models.FileField(blank=True, null=True, upload_to='interviews/')),
                ('voice_confidence_score', models.FloatField(default=0.0, help_text='Level 2 Score')),
                ('voice_fluency_score', models.FloatField(default=0.0)),
                ('voice_passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HRInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True)),
                ('final_status', models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
    ]
